spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: system
    password: nareshit
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
